from typing import Dict, Sequence, Any
import time

from mcp.types import TextContent, Tool

from core.exceptions import SQLExecutionError
from tools.base import ToolsBase
from utils.execute_sql_util import ExecuteSqlUtil
from permission.permission_checker import PermissionChecker
from permission.audit_logger import log_sql_execution, log_permission_denied
from permission.context import get_current_username


class ExecuteSQLTool(ToolsBase):
    """SQL 执行工具类
    
    该工具专门用于执行由 sql_creator 生成的 SQL 语句。它不应该直接执行模型自行构造的 SQL，
    而应在 sql_creator 成功生成 SQL 后调用此工具进行执行。支持执行多条 SQL 语句（以分号分隔）。
    支持数据库、表、列级别的权限检查和审计日志记录。
    用户信息从请求头中自动获取，无需手动传入。
    """
    
    # 工具名称
    name = "execute_sql"
    # 工具描述，包含中英文说明和使用规范
    description = ("该工具仅用于执行由 sql_creator 生成的 SQL。禁止在此工具中直接输入模型自行构造或推测的 SQL 语句。"
                   "通常在 sql_creator 成功生成 SQL 后，才应调用此工具进行执行。"
                    "SQL 执行工具，用于在数据库上执行已生成的 SQL 语句（支持多条，以分号分隔）。"
                    "支持 username 参数进行权限校验，无权限的 SQL 将被拒绝执行。"
                   "This tool is only for executing SQL generated by sql_creator. It is prohibited to input SQL statements "
                   "constructed or inferred by the model directly into this tool. This tool should typically be called for "
                   "execution only after sql_creator successfully generates SQL. SQL execution tool, used to execute generated SQL "
                   "statements on the database (supports multiple statements separated by semicolons)."
                   )


    def get_tool_description(self) -> Tool:
        """获取工具的详细描述信息
        
        返回一个Tool对象，包含工具名称、描述和输入参数模式。
        该描述用于MCP服务识别和调用工具。
        
        Returns:
            Tool: 包含工具描述信息的对象
        """
        return Tool(
            name=self.name,
            description=self.description,
            inputSchema={
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "要执行的SQL语句"
                    },
                    "pool_name": {
                        "type": "string",
                        "description": "线程池名称,若没有指定默认是default"
                    }
                },
                "required": ["query"]
            }
        )


    async def run_tool(self, arguments: Dict[str, Any]) -> Sequence[TextContent]:
        """执行SQL工具
        
        执行传入的SQL语句，并返回执行结果。
        
        Args:
            arguments: 包含执行参数的字典
                - query (str): 要执行的SQL语句
                - pool_name (str, optional): 数据库连接池名称，默认为"default"

        Returns:
            Sequence[TextContent]: 包含执行结果的文本内容序列
            
        Raises:
            SQLExecutionError: 当SQL执行出现错误时抛出
        """
        # 检查参数中是否包含必需的query字段
        if "query" not in arguments:
            return [TextContent(type="text", text="错误: 缺少查询语句")]

        # 获取要执行的SQL语句
        query = arguments["query"]
        
        # 从请求上下文获取当前用户名（用于权限校验）
        username = get_current_username()
        if not username or username == "anonymous":
            return [TextContent(type="text", text="错误: 未提供用户认证信息。请在请求头中设置 X-Username 和 X-API-Key")]

        # 获取连接池名称，如果没有指定则使用默认值"default"
        pool_name = arguments.get("pool_name", "default")

        # 执行权限检查（如果提供了用户名）
        try:
            checker = PermissionChecker(username)
            perm_result = checker.check_sql_permission(query, pool_name)
            
            if not perm_result.allowed:
                # 记录权限拒绝事件
                log_permission_denied(
                    username=username,
                    sql=query,
                    reason=perm_result.message,
                    level=perm_result.level.value if hasattr(perm_result.level, 'value') else str(perm_result.level),
                    pool_name=pool_name
                )
                return [TextContent(type="text", text=f"❌ 权限不足: {perm_result.message}")]
        except Exception as e:
            # 权限检查失败，记录错误但不阻止执行
            import logging
            logging.getLogger(__name__).error(f"权限检查异常: {e}")

        # 记录 SQL 执行开始时间
        start_time = time.time()
        
        try:
            # 执行多条SQL语句
            sql_results = ExecuteSqlUtil.execute_multiple_statements(pool_name, query)

            # 计算执行时间
            execution_time = (time.time() - start_time) * 1000  # 毫秒

            # 格式化执行结果
            results = []
            for result in sql_results:
                formatted_result = ExecuteSqlUtil.format_result(result)
                results.append(formatted_result)
            
            final_result = "\n---\n".join(results)

            # 记录审计日志
            log_sql_execution(
                username=username,
                sql=query,
                pool_name=pool_name,
                success=True,
                result=final_result[:1000] if len(final_result) > 1000 else final_result,  # 限制结果长度
                execution_time=execution_time
            )

            # 将所有结果用分隔符连接并返回
            return [TextContent(type="text", text=final_result)]

        # 捕获SQL执行错误并返回错误信息
        except SQLExecutionError as e:
            # 计算执行时间
            execution_time = (time.time() - start_time) * 1000
            
            # 记录审计日志
            log_sql_execution(
                username=username,
                sql=query,
                pool_name=pool_name,
                success=False,
                result=str(e),
                execution_time=execution_time
            )
            
            return [TextContent(type="text", text=str(e))]