from typing import Dict, Sequence, Any
import time
import re

from mcp.types import TextContent, Tool

from core.exceptions import SQLExecutionError
from tools.base import ToolsBase
from utils.execute_sql_util import ExecuteSqlUtil
from permission.permission_checker import PermissionChecker
from permission.audit_logger import log_sql_execution, log_permission_denied
from permission.context import get_current_username


class ExecuteSQLTool(ToolsBase):
    """SQL 执行工具类
    
    该工具专门用于执行由 sql_creator 生成的 SQL 语句。它不应该直接执行模型自行构造的 SQL，
    而应在 sql_creator 成功生成 SQL 后调用此工具进行执行。支持执行多条 SQL 语句（以分号分隔）。
    支持数据库、表、列级别的权限检查和审计日志记录。
    用户信息从请求头中自动获取，无需手动传入。
    """
    
    # 工具名称
    name = "execute_sql"
    # 工具描述，包含中英文说明和使用规范
    description = ("该工具仅用于执行由 sql_creator 生成的 SQL。禁止在此工具中直接输入模型自行构造或推测的 SQL 语句。"
                   "通常在 sql_creator 成功生成 SQL 后，才应调用此工具进行执行。"
                    "SQL 执行工具，用于在数据库上执行已生成的 SQL 语句（支持多条，以分号分隔）。"
                    "支持 username 参数进行权限校验，无权限的 SQL 将被拒绝执行。"
                   "This tool is only for executing SQL generated by sql_creator. It is prohibited to input SQL statements "
                   "constructed or inferred by the model directly into this tool. This tool should typically be called for "
                   "execution only after sql_creator successfully generates SQL. SQL execution tool, used to execute generated SQL "
                   "statements on the database (supports multiple statements separated by semicolons)."
                   )


    def get_tool_description(self) -> Tool:
        """获取工具的详细描述信息
        
        返回一个Tool对象，包含工具名称、描述和输入参数模式。
        该描述用于MCP服务识别和调用工具。
        
        Returns:
            Tool: 包含工具描述信息的对象
        """
        return Tool(
            name=self.name,
            description=self.description,
            inputSchema={
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "要执行的SQL语句"
                    },
                    "pool_name": {
                        "type": "string",
                        "description": "线程池名称,若没有指定默认是default"
                    }
                },
                "required": ["query"]
            }
        )

    def _apply_row_filter(self, sql: str, row_filter: str) -> str:
        """自动将行过滤条件应用到 SQL 查询中
        
        Args:
            sql: 原始 SQL 语句
            row_filter: 行过滤条件（如 "department = 'sales'"）
            
        Returns:
            添加了行过滤条件的 SQL 语句
        """
        if not row_filter or not sql.strip().upper().startswith('SELECT'):
            return sql
        
        # 解析 SQL 语句，查找表名和现有的 WHERE 子句
        sql_upper = sql.strip().upper()
        
        # 提取表名（处理简单查询）
        # 匹配 FROM table_name 或 FROM schema.table_name
        from_pattern = r'(?:FROM|JOIN)\s+(?:(\w+)\.)?(\w+)'
        tables = re.findall(from_pattern, sql_upper)
        
        if not tables:
            return sql
        
        # 检查是否已有 WHERE 子句
        has_where = re.search(r'\bWHERE\b', sql_upper)
        
        # 构建过滤条件 - 直接在现有 WHERE 后添加 AND，或创建新的 WHERE
        if has_where:
            # 在最后一个 WHERE 后添加 AND 条件
            # 找到最后一个 WHERE 的位置
            last_where_pos = sql_upper.rfind('WHERE')
            # 在原 SQL 中找到对应位置
            original_sql = sql
            where_pos_in_original = len(sql) - len(sql_upper[last_where_pos:]) + sql_upper[last_where_pos:].find('WHERE')
            
            # 在 WHERE 后插入 AND 和过滤条件
            # 找到 WHERE 后第一个 AND/ORDER/GROUP 等关键字的位置
            remaining = sql[where_pos_in_original + 5:].strip()
            
            # 判断后续是否有 AND/OR/ORDER/GROUP/HAVING/LIMIT 等
            keywords = ['ORDER', 'GROUP', 'HAVING', 'LIMIT', 'UNION', 'OFFSET']
            keyword_match = re.match(r'(AND|OR)\s+', remaining, re.IGNORECASE)
            
            if keyword_match:
                # 已经有 AND/OR，插入到它们之前
                pos = where_pos_in_original + 5 + len(keyword_match.group(0))
                return sql[:pos] + f"({row_filter}) AND " + sql[pos:]
            else:
                # 添加 AND 条件
                # 找到需要插入的位置（在 ORDER/GROUP 等之前，或在语句末尾）
                insert_pos = len(sql)
                for keyword in keywords:
                    match = re.search(rf'\b{keyword}\b', remaining, re.IGNORECASE)
                    if match:
                        keyword_pos = remaining.find(match.group(0))
                        if keyword_pos < insert_pos - len(remaining):
                            insert_pos = where_pos_in_original + 5 + keyword_pos
                            break
                
                return sql[:insert_pos] + f" WHERE ({row_filter})" + sql[insert_pos:]
        else:
            # 没有 WHERE 子句，添加到表名后
            # 查找 FROM 后的表名结束位置
            from_match = re.search(from_pattern, sql_upper)
            if from_match:
                # 找到表名结束位置，在原 SQL 中
                table_end_in_original = from_match.end()
                # 找到表名实际结束位置（在原 SQL 中）
                original_from_pos = sql.find(from_match.group(0))
                table_name = from_match.group(2)
                table_name_end_in_original = original_from_pos + len(table_name)
                
                # 在表名后添加 WHERE 条件
                return sql[:table_name_end_in_original] + f" WHERE ({row_filter})" + sql[table_name_end_in_original:]
        
        return sql

    async def run_tool(self, arguments: Dict[str, Any]) -> Sequence[TextContent]:
        """执行SQL工具
        
        执行传入的SQL语句，并返回执行结果。
        
        Args:
            arguments: 包含执行参数的字典
                - query (str): 要执行的SQL语句
                - pool_name (str, optional): 数据库连接池名称，默认为"default"

        Returns:
            Sequence[TextContent]: 包含执行结果的文本内容序列
            
        Raises:
            SQLExecutionError: 当SQL执行出现错误时抛出
        """
        # 检查参数中是否包含必需的query字段
        if "query" not in arguments:
            return [TextContent(type="text", text="错误: 缺少查询语句")]

        # 获取要执行的SQL语句
        query = arguments["query"]
        
        # 从请求上下文获取当前用户名（用于权限校验）
        username = get_current_username()
        if not username or username == "anonymous":
            return [TextContent(type="text", text="错误: 未提供用户认证信息。请在请求头中设置 X-Username 和 X-API-Key")]

        # 获取连接池名称，如果没有指定则使用默认值"default"
        pool_name = arguments.get("pool_name", "default")

        # 执行权限检查（如果提供了用户名）
        row_filter = None
        try:
            checker = PermissionChecker(username)
            perm_result = checker.check_sql_permission(query, pool_name)
            
            if not perm_result.allowed:
                # 记录权限拒绝事件
                log_permission_denied(
                    username=username,
                    sql=query,
                    reason=perm_result.message,
                    level=perm_result.level.value if hasattr(perm_result.level, 'value') else str(perm_result.level),
                    pool_name=pool_name
                )
                return [TextContent(type="text", text=f"❌ 权限不足: {perm_result.message}")]
            
            # 获取行过滤条件（权限检查通过后获取）
            row_filter = perm_result.row_filter
            
        except Exception as e:
            # 权限检查失败，记录错误并拒绝执行
            import logging
            logging.getLogger(__name__).error(f"权限检查异常: {e}")
            return [TextContent(type="text", text=f"❌ 权限检查失败(系统错误): {str(e)}")]

        # 记录 SQL 执行开始时间
        start_time = time.time()
        
        # 应用行过滤条件
        original_query = query
        if row_filter:
            query = self._apply_row_filter(query, row_filter)
            import logging
            logging.getLogger(__name__).info(f"应用行过滤条件: {row_filter} -> {query}")
        
        try:
            # 执行多条SQL语句
            sql_results = ExecuteSqlUtil.execute_multiple_statements(pool_name, query)

            # 计算执行时间
            execution_time = (time.time() - start_time) * 1000  # 毫秒

            # 格式化执行结果
            results = []
            for result in sql_results:
                formatted_result = ExecuteSqlUtil.format_result(result)
                results.append(formatted_result)
            
            final_result = "\n---\n".join(results)

            # 记录审计日志
            log_sql_execution(
                username=username,
                sql=original_query,
                pool_name=pool_name,
                success=True,
                result=final_result[:1000] if len(final_result) > 1000 else final_result,  # 限制结果长度
                execution_time=execution_time
            )

            # 将所有结果用分隔符连接并返回
            return [TextContent(type="text", text=final_result)]

        # 捕获SQL执行错误并返回错误信息
        except SQLExecutionError as e:
            # 计算执行时间
            execution_time = (time.time() - start_time) * 1000
            
            # 记录审计日志
            log_sql_execution(
                username=username,
                sql=original_query,
                pool_name=pool_name,
                success=False,
                result=str(e),
                execution_time=execution_time
            )
            
            return [TextContent(type="text", text=str(e))]
